swagger: '2.0'
info:
  x-21-github-project-url: https://github.com/beaucronin/ip-lookup-402
  title: IP Location Lookup
  description: IP and host locations
  termsOfService: "https://opensource.org/licenses/MIT"
  x-21-usage: "Send GET request to server to get location information for an IP"
  x-21-quick-buy: "21 buy url http://10.244.182.5:5000/json/1.2.3.4"
  x-21-category: utilities
  x-21-app-image: 'https://cdn.filestackcontent.com/tEZC9LbjSAy6DPSGYPVt'
  x-21-total-price:
    min: 2
    max: 2
  contact:
    name: 'Beau Cronin'
    email: beau@21.co
    url: https://21.co/beau21
  license:
    name: MIT LICENSE
    url: https://opensource.org/licenses/MIT
  x-21-keywords:
    - IP
  version: '0.1'
host: 10.244.182.5:5000
schemes:
  - http
basePath: /
x-21-manifest-path: /manifest
